export interface ItemStatCostData {
    Stat: string;
    ID: string;
    ['Send Other']: string;
    Signed: string;
    ['Send Bits']: string;
    ['Send Param Bits']: string;
    UpdateAnimRate: string;
    Saved: string;
    CSvSigned: string;
    CSvBits: string;
    CSvParam: string;
    fCallback: string;
    fMin: string;
    MinAccr: string;
    Encode: string;
    Add: string;
    Multiply: string;
    Divide: string;
    ValShift: string;
    ['1#09-Save Bits']: string;
    ['1#09-Save Add']: string;
    ['Save Bits']: string;
    ['Save Add']: string;
    ['Save Param Bits']: string;
    keepzero: string;
    op: string;
    ['op param']: string;
    ['op base']: string;
    ['op stat1']: string;
    ['op stat2']: string;
    ['op stat3']: string;
    direct: string;
    maxstat: string;
    itemspecific: string;
    damagerelated: string;
    itemevent1: string;
    itemeventfunc1: string;
    itemevent2: string;
    itemeventfunc2: string;
    descpriority: string;
    descfunc: string;
    descval: string;
    descstrpos: string;
    descstrneg: string;
    descstr2: string;
    dgrp: string;
    dgrpfunc: string;
    dgrpval: string;
    dgrpstrpos: string;
    dgrpstrneg: string;
    dgrpstr2: string;
    stuff: string;
    ['*eol']: string;
}